// examples/react-e-commerce-app/src/pages/AuthRedirect.tsx
import { useNavigate, useSearchParams } from 'react-router-dom';
import { useEffect, useState } from 'react';
import { APIError } from 'altogic';
import altogic from '../libs/altogic';
import { useAuthStore } from '../store';
import { User } from '../types/altogic';
import Button from '../components/ui/Button';

export default function AuthRedirect() {
	const [errors, setErrors] = useState<APIError>();
	const { setUser, setSession } = useAuthStore();
	const [searchParams] = useSearchParams();
	const navigate = useNavigate();

	useEffect(() => {
		loginWithToken().catch(console.error);
	}, []);

	async function loginWithToken() {
		const token = searchParams.get('access_token');
		if (!token) {
			return setErrors({
				status: 400,
				statusText: 'Bad Request',
				items: [
					{
						message: 'Access token is missing.',
						origin: '',
						code: ''
					}
				]
			});
		}
		const { user, session, errors: apiErrors } = await altogic.auth.getAuthGrant(token);
		if (!apiErrors) {
			setSession(session);
			setUser(user as User);
			navigate('/profile');
		} else {
			setErrors(apiErrors);
		}
	}

	return (
		<section className="h-screen flex flex-col gap-4 justify-center items-center">
			{!errors ? (
				<div className="text-center">
					<p className="text-6xl">Please wait</p>
					<p className="text-3xl">You're redirecting to your profile...</p>
				</div>
			) : (
				<>
					{errors.items.map((error, key) => (
						<div key={key} className="text-center text-red-500 text-3xl">
							<p>{error.message}</p>
						</div>
					))}
					<Button as="link" href="/">
						Go to Home
					</Button>
				</>
			)}
		</section>
	);
}

// examples/authentication/Ionic Vue/src/views/AuthRedirect.vue
<script lang="ts">
import { defineComponent, ref, onMounted } from 'vue';
import altogic from '@/libs/altogic';
import { APIError } from 'altogic';
import { useRoute, useRouter } from 'vue-router';
import { useAuthStore } from '@/store/auth';
import { IonPage, IonContent } from '@ionic/vue';

export default defineComponent({
	name: 'AuthRedirectPage',
	components: { IonPage, IonContent },
	setup() {
		const auth = useAuthStore();
		const { access_token } = useRoute().query;
		const router = useRouter();
		const errors = ref<APIError | null>(null);

		onMounted(() => {
			loginWithToken();
		});

		async function loginWithToken() {
			const { user, session, errors: apiErrors } = await altogic.auth.getAuthGrant(access_token?.toString());
			if (!apiErrors) {
				auth.setSession(session);
				auth.setUser(user);
				await router.push('/profile');
			} else {
				errors.value = apiErrors;
			}
		}
		return {
			auth,
			errors,
		};
	},
});
</script>
<template>
	<ion-page>
		<ion-content :fullscreen="true">
			<section class="h-screen flex flex-col gap-4 justify-center items-center">
				<div class="text-center" v-if="!errors">
					<p class="text-6xl">Please wait</p>
					<p class="text-3xl">You're redirecting to your profile...</p>
				</div>
				<div class="text-center text-red-500 text-3xl" v-else>
					<p :key="index" v-for="(error, index) in errors.items">{{ error.message }}</p>
				</div>
			</section>
		</ion-content>
	</ion-page>
</template>
