// examples/authentication/Nuxt.js 2/pages/profile.vue
<script>
import Avatar from '~/components/Avatar';
import Sessions from '~/components/Sessions';
import UserInfo from '~/components/UserInfo';
export default {
	middleware: ['auth'],
	components: {
		Avatar,
		Sessions,
		UserInfo,
	},
};
</script>
<template>
	<div>
		<section class="h-screen py-4 space-y-4 flex flex-col text-center items-center">
			<Avatar />
			<UserInfo />
			<Sessions />
			<a href="/api/logout" class="bg-gray-400 rounded py-2 px-3 text-white"> Logout </a>
		</section>
	</div>
</template>

// examples/authentication/SvelteKit/src/routes/profile/+page.svelte
<script>
	import { authStore, sessionStore } from '../../store/auth.store';
	import UserInfo from '../../components/UserInfo.svelte';
	import Avatar from '../../components/Avatar.svelte';
	import Sessions from '../../components/Sessions.svelte';
	export let data;
</script>

<section class="h-screen py-4 space-y-4 flex flex-col text-center items-center">
	<Avatar />
	<UserInfo />
	<Sessions sessions={data.allSessions} />
	<a
		href="/api/logout"
		class="border py-2 px-3 border-gray-500 hover:bg-gray-500 hover:text-white transition shrink-0"
	>
		Sign Out
	</a>
</section>
