// examples/authentication/Angular/src/app/pages/login-with-magic-link/login-with-magic-link.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../shared/auth.service';
import altogic from '../../libs/altogic';
import { APIError } from 'altogic';

@Component({
	selector: 'app-login-with-magic-link',
	templateUrl: './login-with-magic-link.component.html',
})
export class LoginWithMagicLinkComponent implements OnInit {
	magicForm = this.fb.group({
		email: ['', Validators.required],
	});
	errors: APIError | null = null;
	loading = false;
	showMessage = false;
	constructor(private fb: FormBuilder, private router: Router, private authService: AuthService) {}

	ngOnInit(): void {}

	async submitHandler() {
		const { email } = this.magicForm.value;
		if (!email) return;
		this.loading = true;
		this.errors = null;
		this.showMessage = false;

		const { errors } = await altogic.auth.sendMagicLinkEmail(email);
		this.loading = false;

		if (errors) {
			this.errors = errors;
			return;
		}

		this.showMessage = true;
		this.magicForm.reset();
	}
}

<section class="flex flex-col items-center justify-center h-96 gap-4">
	<form (ngSubmit)="submitHandler()" [formGroup]="magicForm" class="flex flex-col gap-2 w-full md:w-96">
		<h1 class="self-start text-3xl font-bold">Login with magic link</h1>

		<div *ngIf="showMessage" class="bg-green-600 text-white text-[13px] p-2">
			Your magic link has been sent to your email address.
		</div>

		<ng-container *ngIf="errors">
			<div *ngFor="let error of errors.items" class="bg-red-600 text-white text-[13px] p-2">
				<p>{{ error.message }}</p>
			</div>
		</ng-container>

		<input formControlName="email" type="email" placeholder="Type your email" required />
		<div class="flex justify-between gap-4 items-start">
			<a class="text-indigo-600" routerLink="/register">Don't have an account? Register now</a>
			<button
				type="submit"
				[disabled]="!magicForm.valid || loading"
				class="border py-2 px-3 border-gray-500 hover:bg-gray-500 hover:text-white transition shrink-0"
			>
				Send magic link
			</button>
		</div>
	</form>
</section>

// examples/authentication/Nuxt.js 3/pages/login-with-magic-link.vue
<script setup lang="ts">
import altogic from '~/libs/altogic';

const successMessage = ref('');
const loading = ref(false);
const email = ref('');
const errors = ref(null);

definePageMeta({
    middleware: ['guest'],
});
useHead({
    title: 'Login with magic link',
});

async function loginHandler() {
    loading.value = true;
    errors.value = null;
    const { errors: apiErrors } = await altogic.auth.sendMagicLinkEmail(email.value);
    loading.value = false;
    if (apiErrors) {
        errors.value = apiErrors;
    } else {
        email.value = '';
        successMessage.value = 'Email sent! Check your inbox.';
    }
}
</script>

<template>
    <section class="flex flex-col items-center justify-center h-96 gap-4">
        <form @submit.prevent="loginHandler" class="flex flex-col gap-2 w-full md:w-96">
            <h1 class="self-start text-3xl font-bold">Login with magic link</h1>

            <div v-if="successMessage" class="bg-green-600 text-white text-[13px] p-2">
                {{ successMessage }}
            </div>

            <div v-if="errors" class="bg-red-600 text-white text-[13px] p-2">
                <p v-for="(error, index) in errors.items" :key="index">
                    {{ error.message }}
                </p>
            </div>

            <input v-model="email" type="email" placeholder="Type your email" required />
            <div class="flex justify-between gap-4">
                <NuxtLink class="text-indigo-600" to="/register">Don't have an account? Register now</NuxtLink>
                <button
                    :disabled="loading"
                    type="submit"
                    class="border py-2 px-3 border-gray-500 hover:bg-gray-500 hover:text-white transition shrink-0"
                >
                    Send magic link
                </button>
            </div>
        </form>
    </section>
</template>
