// examples/authentication/Ionic Vue/src/views/Home.vue
<script lang="ts">
import { defineComponent } from 'vue';
import { IonPage, IonContent } from '@ionic/vue';

export default defineComponent({
	name: 'HomePage',
	components: { IonContent, IonPage },
});
</script>

<template>
	<ion-page>
		<ion-content :fullscreen="true">
			<div class="flex justify-center gap-2 h-screen items-center">
				<router-link class="border px-4 py-2 font-medium text-sm" to="/login-with-magic-link">
					Login With Magic Link
				</router-link>
				<router-link class="border px-4 py-2 font-medium text-sm" to="/login">Login</router-link>
				<router-link class="border px-4 py-2 font-medium text-sm" to="/register">Register</router-link>
			</div>
		</ion-content>
	</ion-page>
</template>

// examples/authentication/Angular/src/app/pages/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
	selector: 'app-home',
	templateUrl: './home.component.html',
})
export class HomeComponent implements OnInit {
	constructor() {}

	ngOnInit(): void {}
}

<div class="flex items-center justify-center gap-4 h-screen">
  <a routerLink="/login-with-magic-link" class="border px-4 py-2 font-medium text-xl">
  Login With Magic Link
  </a>
  <a routerLink="/login" class="border px-4 py-2 font-medium text-xl">
  Login
  </a>
  <a routerLink="/register" class="border px-4 py-2 font-medium text-xl">
  Register
  </a>
</div>
