// examples/react-quickstart-blog-app/src/components/SingleBlog.js
import { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import altogic from "../helpers/altogic";

const SingleBlog = () => {
  // Stores the id value of the params in URL
  const { id } = useParams();

  // Single blog instance fecthed from the database
  const [blog, setBlog] = useState(null);

  useEffect(() => {
    const getBlog = async () => {
      // Gets the single blog object with given ID
      const result = await altogic.db.model("blogs").object(id).get();
      if (!result.errors) {
        setBlog(result.data);
      }
    };
    getBlog();
  }, []);
  return (
    <div className="text-left p-2 lg:mx-64">
      <Link className="text-xs text-blue-600" to="/">
        Back to Blogs
      </Link>
      {blog ? (
        <div className="text-sm mt-5 text-center ">
          <h2 className="text-xl my-2 ">{blog.title}</h2>
          <div className="text-sm text-gray-600">
            <div dangerouslySetInnerHTML={{ __html: blog.content }}></div>
          </div>
          <div className="mt-3 text-xs text-gray-500">{blog.createdAt}</div>
        </div>
      ) : null}
    </div>
  );
};

export default SingleBlog;

// examples/vue-quickstart-blog-app/src/components/SingleBlog.vue
<template>
  <div class="text-left p-2 lg:mx-64">
    <router-link class="text-xs text-blue-600" to="/">
      Back to Blogs
    </router-link>
    <div class="text-sm mt-5 text-center" v-if="blog">
      <h2 class="text-xl my-2">{{ blog.title }}</h2>
      <div class="text-sm text-gray-600">
        <div v-html="blog.content"></div>
      </div>
      <div class="mt-3 text-xs text-gray-500">{{ blog.createdAt }}</div>
    </div>
  </div>
</template>

<script>
import altogic from "../helpers/altogic";

export default {
  name: "SingleBlog",
  data() {
    return {
      blog: null,
    };
  },
  async mounted() {
    // Fetch the blog data after mounted
    const result = await altogic.db
      .model("blogs")
      .object(this.$route.params.id)
      .get();
    if (!result.errors) {
      this.blog = result.data;
    }
  },
};
</script>
