// examples/authentication/Solid.js/src/pages/Login.jsx
import { A, useNavigate } from '@solidjs/router';
import { batch, createSignal, For } from 'solid-js';
import altogic from '../libs/altogic';
import { useAuth } from '../context/AuthContext';

export default function Login() {
	const [email, setEmail] = createSignal('');
	const [password, setPassword] = createSignal('');
	const [errors, setErrors] = createSignal(null);
	const [loading, setLoading] = createSignal(false);
	const navigate = useNavigate();
	const [_, { setUser, setSession }] = useAuth();

	const handleSubmit = async e => {
		e.preventDefault();
		setErrors(null);
		setLoading(true);
		const { session, errors: apiErrors, user } = await altogic.auth.signInWithEmail(email(), password());
		setLoading(false);

		if (apiErrors) {
			return setErrors(apiErrors);
		}

		batch(() => {
			setEmail('');
			setPassword('');
			setUser(user);
			setSession(session);
		});

		navigate('/profile');
	};

	return (
		<section class="flex flex-col items-center justify-center h-96 gap-4">
			<form onSubmit={handleSubmit} class="flex flex-col gap-2 w-full md:w-96">
				<h1 class="self-start text-3xl font-bold">Login to your account</h1>

				{errors() && (
					<div class="bg-red-600 text-white text-[13px] p-2">
						<For each={errors().items}>{error => <p>{error.message}</p>}</For>
					</div>
				)}

				<input
					value={email()}
					onInput={e => setEmail(e.currentTarget.value)}
					type="email"
					placeholder="Type your email"
					required
				/>
				<input
					value={password()}
					onInput={e => setPassword(e.currentTarget.value)}
					type="password"
					placeholder="Type your password"
					required
				/>
				<div class="flex justify-between gap-4">
					<A class="text-indigo-600" href="/register">
						Don't have an account? Register now
					</A>
					<button
						disabled={loading()}
						type="submit"
						class="border py-2 px-3 border-gray-500 hover:bg-gray-500 hover:text-white transition shrink-0"
					>
						Login
					</button>
				</div>
			</form>
		</section>
	);
}

// examples/authentication/Angular/src/app/pages/login/login.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormControl, Validators } from '@angular/forms';
import altogic from '../../libs/altogic';
import { APIError } from 'altogic';
import { Router } from '@angular/router';
import { AuthService } from '../../shared/auth.service';

@Component({
	selector: 'app-login',
	templateUrl: './login.component.html',
})
export class LoginComponent implements OnInit {
	loginForm = this.fb.group({
		email: ['', Validators.required],
		password: ['', Validators.required],
	});
	errors: APIError | null = null;
	loading = false;

	constructor(private fb: FormBuilder, private router: Router, private authService: AuthService) {}
	ngOnInit(): void {}

	async submitHandler() {
		const { email, password } = this.loginForm.value;
		if (!email || !password) return;
		this.loading = true;
		this.errors = null;

		const { user, session, errors } = await altogic.auth.signInWithEmail(email, password);
		this.loading = false;

		if (errors) {
			this.errors = errors;
			return;
		}

		this.authService.setUserAndSession(user, session);
		await this.router.navigate(['profile']);
	}
}

<section class="flex flex-col items-center justify-center h-96 gap-4">
	<form (ngSubmit)="submitHandler()" [formGroup]="loginForm" class="flex flex-col gap-2 w-full md:w-96">
		<h1 class="self-start text-3xl font-bold">Login to your account</h1>
		<ng-container *ngIf="errors">
			<div *ngFor="let error of errors.items" class="bg-red-600 text-white text-[13px] p-2">
				<p>{{ error.message }}</p>
			</div>
		</ng-container>
		<input formControlName="email" type="email" placeholder="Type your email" required />
		<input formControlName="password" type="password" placeholder="Type your password" required />
		<div class="flex justify-between gap-4 items-start">
			<a class="text-indigo-600" routerLink="/register">Don't have an account? Register now</a>
			<button
				type="submit"
				[disabled]="!loginForm.valid || loading"
				class="border py-2 px-3 border-gray-500 hover:bg-gray-500 hover:text-white transition shrink-0"
			>
				Login
			</button>
		</div>
	</form>
</section>
