// examples/authentication/Ionic Angular/src/app/components/user-info/user-info.component.ts
import { Component, OnInit } from '@angular/core';
import { FormControl, Validators } from '@angular/forms';
import { AuthService } from '../../shared/auth.service';
import { User } from 'altogic';
import altogic from '../../libs/altogic';

@Component({
	selector: 'app-user-info',
	templateUrl: './user-info.component.html',
})
export class UserInfoComponent implements OnInit {
	errors: null | string = null;
	changeMode = false;
	loading = false;
	name = new FormControl(this.getUserName(), [Validators.required]);
	constructor(private authService: AuthService) {}
	getUserName() {
		return this.authService.user?.name;
	}
	async saveName() {
		this.loading = true;
		this.errors = null;

		const { data, errors: apiErrors } = await altogic.db
			.model('users')
			.object(this.authService.user?._id)
			.update({ name: this.name.value });

		if (apiErrors) {
			this.errors = apiErrors.items[0].message;
		} else {
			this.authService.setUser(data as User);
		}

		this.loading = false;
		this.changeMode = false;
	}
	ngOnInit() {}
}

<section class="border p-4 container w-full">
  <div class="flex items-center justify-center" *ngIf="changeMode">
    <input
      (keydown.enter)="saveName()"
      autofocus
      [formControl]="name"
      type="text"
      class="border-none text-3xl text-center text-white bg-transparent border"
    />
  </div>
  <div class="space-y-4 flex flex-col items-center" *ngIf="!changeMode">
    <h1 class="text-3xl text-center">Hello, {{ getUserName() }}</h1>
    <button (click)="changeMode = true" class="border p-2 bg-white text-black">Change name</button>
  </div>
  <div *ngIf="errors">{{ errors }}</div>
</section>

// examples/authentication/Ionic Vue/src/components/UserInfo.vue
<script lang="ts">
import { ref, defineComponent } from 'vue';
import altogic from '../libs/altogic';
import { useAuthStore } from '@/store/auth';
import { User } from 'altogic';

export default defineComponent({
	name: 'UserInfoComponents',
	setup() {
		const auth = useAuthStore();
		const username = ref(auth?.user?.name);
		const loading = ref(false);
		const inputRef = ref<HTMLInputElement>();
		const changeMode = ref(false);
		const errors = ref<string | null>(null);

		function openChangeMode() {
			changeMode.value = true;
			setTimeout(() => {
				inputRef.value?.focus();
			}, 100);
		}

		async function saveName() {
			loading.value = true;
			errors.value = null;

			let { data, errors: apiErrors } = await altogic.db
				.model('users')
				.object(auth.user?._id)
				.update({ name: username.value });
			let user = data as User;

			if (apiErrors) {
				errors.value = apiErrors.items[0].message;
				return;
			} else {
				username.value = user.name;
				auth.setUser(user);
			}

			loading.value = false;
			changeMode.value = false;
		}

		return {
			auth,
			username,
			loading,
			inputRef,
			changeMode,
			errors,
			openChangeMode,
			saveName,
		};
	},
});
</script>

<template>
	<section class="border p-4 w-full">
		<div class="flex items-center justify-center" v-if="changeMode">
			<input
				@keyup.enter="saveName"
				ref="inputRef"
				type="text"
				v-model="username"
				class="bg-transparent text-white border-none text-3xl text-center"
			/>
		</div>
		<div class="space-y-4 flex flex-col items-center" v-else>
			<h1 class="text-3xl text-center">Hello, {{ auth.user?.name }}</h1>
			<button @click="openChangeMode" class="bg-white text-black p-2">Change name</button>
		</div>
		<div v-if="errors">
			{{ errors }}
		</div>
	</section>
</template>
