// examples/authentication/SvelteKit/src/components/UserInfo.svelte
<script>
	import { authStore } from '../store/auth.store';
	import altogic from '../libs/altogic.js';

	let changeMode = false;
	let name = $authStore?.name || '';
	let errors = null;

	const handleNameChange = () => {
		changeMode = true;
	};

	const handleKeyDown = async (e) => {
		if (e.code === 'Enter') {
			errors = null;

			const { data: updatedUser, errors: apiErrors } = await altogic.db
				.model('users')
				.object($authStore._id)
				.update({ name });

			if (apiErrors) errors = apiErrors.items[0].message;
			else authStore.set(updatedUser);

			changeMode = false;
		}
	};
</script>

<section class="border p-4 w-full">
	{#if changeMode}
		<div class="flex items-center justify-center">
			<input
				type="text"
				class="border-none text-3xl text-center"
				on:keydown={handleKeyDown}
				bind:value={name}
			/>
		</div>
	{:else}
		<div class="space-y-4">
			<h1 class="text-3xl">Hello, {$authStore?.name}</h1>
			<button on:click={handleNameChange} class="border p-2"> Change name </button>
		</div>
	{/if}
	{#if errors}<div>{errors}</div>{/if}
</section>

// examples/authentication/Vue/src/components/UserInfo.vue
<script setup>
import { useAuthStore } from '../stores/auth';
import altogic from '../libs/altogic';
import { ref } from 'vue';
const auth = useAuthStore();

const username = ref(auth?.user?.name);
const loading = ref(false);
const inputRef = ref(null);
const changeMode = ref(false);
const errors = ref(null);

function openChangeMode() {
	changeMode.value = true;
	setTimeout(() => {
		inputRef.value.focus();
	}, 100);
}

async function saveName() {
	loading.value = true;
	errors.value = null;

	const { data, errors: apiErrors } = await altogic.db
		.model('users')
		.object(auth.user._id)
		.update({ name: username.value });

	if (apiErrors) {
		errors.value = apiErrors.items[0].message;
		apiErrors;
	} else {
		username.value = data.name;
		auth.setUser(data);
	}

	loading.value = false;
	changeMode.value = false;
}
</script>

<template>
	<section class="border p-4 w-full">
		<div class="flex items-center justify-center" v-if="changeMode">
			<input
				@keyup.enter="saveName"
				ref="inputRef"
				type="text"
				v-model="username"
				class="border-none text-3xl text-center"
			/>
		</div>
		<div class="space-y-4" v-else>
			<h1 class="text-3xl">Hello, {{ auth?.user?.name }}</h1>
			<button @click="openChangeMode" class="border p-2">Change name</button>
		</div>
		<div v-if="errors">
			{{ errors }}
		</div>
	</section>
</template>
