// examples/authentication/SvelteKit/src/routes/sign-in/+page.svelte
<script>
	import { authStore, sessionStore } from '../../store/auth.store';
	import altogic from '../../libs/altogic.js';
	let loading = false;
	let errors = null;

	const handleSignIn = async (e) => {
		e.preventDefault();
		const [email, password] = e.target;
		try {
			loading = true;

			const res = await fetch('/api/sign-in', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json'
				},
				body: JSON.stringify({
					email: email.value,
					password: password.value
				})
			});

			const { user, session, errors } = await res.json();

			if (errors) throw errors;

			authStore.set(user);
			sessionStore.set(session);

			altogic.auth.setSession(session);
			altogic.auth.setUser(user);
			window.location.href = '/profile';
		} catch (err) {
			errors = err.items;
		} finally {
			loading = false;
		}
	};
</script>

<section class="flex flex-col items-center justify-center h-96 gap-4">
	<form class="flex flex-col gap-2 w-full md:w-96" on:submit={handleSignIn}>
		<h1 class="self-start text-3xl font-bold">Login to your account</h1>
		{#if errors}
			<div class="bg-red-600 text-white text-[13px] p-2">
				{#each errors as { message }}
					<p>{message}</p>
				{/each}
			</div>
		{/if}

		<input type="email" placeholder="Type your email" />
		<input autoComplete="new-password" type="password" placeholder="Type your password" />
		<div class="flex justify-between gap-4">
			<a class="text-indigo-600" href="/sign-up">Don't have an account? Register now</a>
			<button
				type="submit"
				class="border py-2 px-3 border-gray-500 hover:bg-gray-500 hover:text-white transition shrink-0"
				disabled={loading}
			>
				Login
			</button>
		</div>
	</form>
</section>

// examples/authentication/Next.js 13/app/sign-in/page.jsx
"use client";

import { useRouter } from "next/navigation";
import Link from "next/link";
import { useState } from "react";

function SignInView() {
  const router = useRouter();

  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(false);

  const handleSignIn = async (e) => {
    e.preventDefault();
    const [email, password] = e.target;
    try {
      setLoading(true);
      const response = await fetch("/api/auth/signIn", {
        method: "POST",
        body: JSON.stringify({
          email: email.value,
          password: password.value,
        }),
      });
      if (!response.ok) {
        const { errors } = await response.json();
        throw errors;
      }
      router.push("/profile");
    } catch (err) {
      setLoading(false);
      setError(err.items);
    }
  };

  return (
    <section className="flex flex-col items-center justify-center h-96 gap-4">
      <form
        className="flex flex-col gap-2 w-full md:w-96"
        onSubmit={handleSignIn}
      >
        <h1 className="self-start text-3xl font-bold">Login to your account</h1>
        {error?.map(({ message }) => (
          <div key={message} className="bg-red-600 text-white text-[13px] p-2">
            <p>{message}</p>
          </div>
        ))}

        <input type="email" placeholder="Type your email" />
        <input
          autoComplete="new-password"
          type="password"
          placeholder="Type your password"
        />
        <div className="flex justify-between gap-4">
          <Link className="text-indigo-600" href="/sign-up">
            Don't have an account? Register now
          </Link>
          <button
            type="submit"
            className="border py-2 px-3 border-gray-500 hover:bg-gray-500 hover:text-white transition shrink-0"
            disabled={loading}
          >
            Login
          </button>
        </div>
      </form>
    </section>
  );
}

export default SignInView;
