// examples/authentication/React/src/components/UserInfo.js
import { useRef, useState } from "react";
import altogic from "../configs/altogic";
import { useAuthContext } from "../contexts/Auth.context";

function UserInfo() {
  const { auth, setAuth } = useAuthContext();
  const inputRef = useRef();

  const [name, setName] = useState("");

  const [changeMode, setChangeMode] = useState(false);
  const [errors, setErrors] = useState(null);

  const handleNameChange = () => {
    setChangeMode(true);
    setTimeout(() => {
      inputRef.current.focus();
    }, 100);
  };

  const handleKeyDown = async (e) => {
    if (e.code === "Enter") {
      setErrors(null);

      const { data: updatedUser, errors: apiErrors } = await altogic.db
        .model("users")
        .object(auth._id)
        .update({ name });

      if (apiErrors) setErrors(apiErrors.items[0].message);
      else setAuth(updatedUser);

      setChangeMode(false);
    }
  };

  return (
    <section className="border p-4 w-full">
      {changeMode ? (
        <div className="flex items-center justify-center">
          <input
            ref={inputRef}
            onKeyDown={handleKeyDown}
            type="text"
            className="border-none text-3xl text-center"
            onChange={(e) => setName(e.target.value)}
            value={name}
          />
        </div>
      ) : (
        <div className="space-y-4">
          <h1 className="text-3xl">Hello, {auth?.name}</h1>
          <button onClick={handleNameChange} className="border p-2">
            Change name
          </button>
        </div>
      )}
      {errors && <div>{errors}</div>}
    </section>
  );
}

export default UserInfo;

// examples/authentication/SvelteKit/src/components/UserInfo.svelte
<script>
	import { authStore } from '../store/auth.store';
	import { altogic } from '../configs/altogic';

	let changeMode = false;
	let name = $authStore.name || '';
	let errors = null;

	const handleNameChange = () => {
		changeMode = true;
	};

	const handleKeyDown = async (e) => {
		if (e.code === 'Enter') {
			errors = null;

			const { data: updatedUser, errors: apiErrors } = await altogic.db
				.model('users')
				.object($authStore._id)
				.update({ name });

			if (apiErrors) errors = apiErrors.items[0].message;
			else authStore.set(updatedUser);

			changeMode = false;
		}
	};
</script>

<section class="border p-4 w-full">
	{#if changeMode}
		<div class="flex items-center justify-center">
			<input
				type="text"
				class="border-none text-3xl text-center"
				on:keydown={handleKeyDown}
				bind:value={name}
			/>
		</div>
	{:else}
		<div class="space-y-4">
			<h1 class="text-3xl">Hello, {$authStore?.name}</h1>
			<button on:click={handleNameChange} class="border p-2"> Change name </button>
		</div>
	{/if}
	{#if errors}<div>{errors}</div>{/if}
</section>
