// examples/authentication/Ionic React/src/pages/auth-redirect.tsx
import React, { useEffect } from "react";
import { RouteComponentProps } from "react-router";
import altogic from "../configs/altogic";
import { useAuthContext } from "../contexts/Auth.context";

const AuthRedirectView: React.FC<RouteComponentProps> = ({
  location,
  history,
}) => {
  const query = new URLSearchParams(location.search);
  const access_token = query.get("access_token");
  const context = useAuthContext();

  const handleToken = async () => {
    if (access_token) {
      const { user, session } = await altogic.auth.getAuthGrant(access_token);
      if (user) {
        context?.setAuth(user);
        context?.setSession(session);
        history.push("/profile");
      } else {
        history.push("/sign-in");
      }
    }
  };

  useEffect(() => {
    handleToken();
  }, [access_token]);

  return (
    <div>
      <div>Redirecting...</div>
    </div>
  );
};

export default AuthRedirectView;

// examples/authentication/SvelteKit/src/routes/auth-redirect/+page.svelte
<script>
	import { authStore, sessionStore } from '../../store/auth.store';
	import { altogic } from '../../configs/altogic';
	import { onMount } from 'svelte';

	const handleToken = async () => {
		const query = new URLSearchParams(window.location.search);
		const access_token = query.get('access_token');
		const { user, session } = await altogic.auth.getAuthGrant(access_token);

		if (user) {
			authStore.set(user);
			sessionStore.set(session);
			window.location.href = '/profile';
		} else {
			window.location.href = '/sign-in';
		}
	};

	onMount(() => {
		handleToken();
	});
</script>

<div>
	<div>Redirecting...</div>
</div>
