// examples/authentication/Ionic React/src/pages/index.tsx
import { IonItem } from "@ionic/react";

const IndexView: React.FC = () => {
  return (
    <div className="flex items-center justify-center gap-4 h-screen">
      <IonItem
        className="px-4 py-2 font-medium text-xl"
        routerLink="/magic-link"
      >
        Login With Magic Link
      </IonItem>
      <IonItem className="px-4 py-2 font-medium text-xl" routerLink="/sign-in">
        Sign In
      </IonItem>
      <IonItem className="px-4 py-2 font-medium text-xl" routerLink="/sign-up">
        Sign Up
      </IonItem>
    </div>
  );
};

export default IndexView;

// examples/authentication/Nuxt.js 2/pages/index.vue
<script>
export default {
	middleware: ['guest'],
	head() {
		return {
			title: 'Altogic Auth Sample With Nuxt2',
		};
	},
};
</script>

<template>
	<div class="flex items-center justify-center gap-4 h-screen">
		<NuxtLink class="border px-4 py-2 font-medium text-xl" to="/login-with-magic-link"
			>Login With Magic Link</NuxtLink
		>
		<NuxtLink class="border px-4 py-2 font-medium text-xl" to="/login">Login</NuxtLink>
		<NuxtLink class="border px-4 py-2 font-medium text-xl" to="/register">Register</NuxtLink>
	</div>
</template>
