// examples/authentication/Nuxt.js 3/pages/auth-redirect.vue
<script setup>
const auth = useAuthStore();
const route = useRoute();
const router = useRouter();
const errors = ref(null);
const { access_token } = route.query;

useHead({
	title: 'Verify your account',
});

onMounted(async () => {
	const { errors: apiErrors, user, session } = await $fetch(`/api/auth/verify-user?access_token=${access_token}`);
	if (apiErrors) {
		errors.value = apiErrors;
		return;
	}
	auth.setUser(user);
	auth.setSession(session);
	await router.push('/profile');
});
</script>

<template>
	<section class="h-screen flex flex-col gap-4 justify-center items-center">
		<div class="text-center" v-if="errors">
			<p class="text-red-500 text-3xl" :key="index" v-for="(error, index) in errors.items">
				{{ error.message }}
			</p>
		</div>
		<div class="text-center" v-else>
			<p class="text-6xl text-black">Please wait</p>
			<p class="text-3xl text-black">You're redirecting to your profile...</p>
		</div>
	</section>
</template>

// examples/authentication/Solid.js/src/pages/AuthRedirect.jsx
import { A, useLocation, useNavigate, useSearchParams } from '@solidjs/router';
import { createSignal, For, onMount } from 'solid-js';
import altogic from '../libs/altogic';
import { useAuth } from '../context/AuthContext';

export default function AuthRedirect() {
	const { access_token } = useLocation().query;
	const navigate = useNavigate();
	const [errors, setErrors] = createSignal(null);
	const [, { setUser, setSession }] = useAuth();

	onMount(() => {
		altogic.auth.getAuthGrant(access_token).then(({ user, session, errors: apiErrors }) => {
			if (apiErrors) {
				return setErrors(apiErrors);
			}

			setUser(user);
			setSession(session);
			navigate('/profile');
		});
	});

	return (
		<section class="h-screen flex flex-col gap-4 justify-center items-center">
			{errors() ? (
				<div class="text-center">
					<For each={errors().items}>{error => <p class="text-red-500 text-3xl">{error.message}</p>}</For>
				</div>
			) : (
				<div class="text-center">
					<p class="text-6xl">Please wait</p>
					<p class="text-3xl">You're redirecting to your profile...</p>
				</div>
			)}
		</section>
	);
}
