// examples/authentication/Svelte/src/App.svelte
<script>
  import { Router, Route, Link } from "svelte-navigator";
  import PrivateRoute from "./components/PrivateRoute.svelte";
  import IndexView from "./routes/index.svelte";
  import AuthRedirectView from "./routes/auth-redirect.svelte";
  import MagicLinkView from "./routes/magic-link.svelte";
  import SignInView from "./routes/sign-in.svelte";
  import SignUpView from "./routes/sign-up.svelte";
  import ProfileView from "./routes/profile.svelte";
</script>

<Router>
  <!-- Public Routes -->
  <Route path="/"><IndexView /></Route>
  <Route path="/auth-redirect"><AuthRedirectView /></Route>
  <Route path="/magic-link"><MagicLinkView /></Route>
  <Route path="/sign-in"><SignInView /></Route>
  <Route path="/sign-up"><SignUpView /></Route>
  <!-- Private Routes -->
  <Route path="/profile">
    <PrivateRoute>
      <ProfileView />
    </PrivateRoute>
  </Route>
</Router>

// examples/authentication/React/src/App.js
import { BrowserRouter as Router, Route, Routes } from "react-router-dom";
import PrivateRoute from "./components/PrivateRoute";

import AuthProvider from "./contexts/Auth.context";
import AuthRedirectView from "./pages/auth-redirect";
import IndexView from "./pages/index";
import MagicLinkView from "./pages/magic-link";
import ProfileView from "./pages/profile";
import SignInView from "./pages/sign-in";
import SignUpView from "./pages/sign-up";

export default function App() {
  return (
    <AuthProvider>
      <Router>
        <Routes>
          {/* Public Routes */}
          <Route path="/" element={<IndexView />} />
          <Route path="/auth-redirect" element={<AuthRedirectView />} />
          <Route path="/magic-link" element={<MagicLinkView />} />
          <Route path="/sign-in" element={<SignInView />} />
          <Route path="/sign-up" element={<SignUpView />} />
          {/* Private Routes */}
          <Route
            path="/profile"
            element={
              <PrivateRoute>
                <ProfileView />
              </PrivateRoute>
            }
          />
        </Routes>
      </Router>
    </AuthProvider>
  );
}
