// examples/authentication/SvelteKit/src/components/Sessions.svelte
<script>
	import altogic from '../libs/altogic.js';
	export let sessions;

	const logoutSession = async (session) => {
		const { errors } = await altogic.auth.signOut(session.token);
		if (!errors) {
			sessions = sessions.filter((s) => s.token !== session.token);
		}
	};
</script>

<div class="border p-4 space-y-4">
	<p class="text-3xl">All Sessions</p>
	<ul class="flex flex-col gap-2">
		{#each sessions as session}
			<li class="flex justify-between gap-12">
				<div>
					{#if session.isCurrent}<span> Current Session </span>{/if}
					<span>
						<strong>Device name: </strong>
						{session?.userAgent.device.family}
					</span>
				</div>
				<div class="flex items-center gap-2">
					<span>
						{new Date(session.creationDtm).toLocaleDateString('en-US')}
					</span>
					{#if !session.isCurrent}
						<button
							class="border grid place-items-center p-2 h-8 w-8 aspect-square leading-none"
							on:click={() => logoutSession(session)}
						>
							X
						</button>
					{/if}
				</div>
			</li>
		{/each}
	</ul>
</div>

// examples/authentication/Remix/app/components/Sessions.jsx
import altogic from '~/libs/altogic';
import { useState } from 'react';

export default function Sessions({ sessions }) {
	const [sessionsList, setSessionsList] = useState(sessions);
	altogic.auth.setSession({ token: sessions.find(s => s.isCurrent).token });

	const logoutSession = async session => {
		const { errors } = await altogic.auth.signOut(session.token);
		if (!errors) {
			setSessionsList(prev => prev.filter(s => s.token !== session.token));
		}
	};

	return (
		<div className="border p-4 space-y-4">
			<p className="text-3xl">All Sessions</p>
			<ul className="flex flex-col gap-2">
				{sessionsList.map(session => (
					<li key={session.token} className="flex justify-between gap-12">
						<div>
							{session?.isCurrent ? (
								<span>Current Sessions</span>
							) : (
								<span>
									<strong>Device name: </strong>
									{session?.userAgent?.device?.family}
								</span>
							)}
						</div>
						<div className="flex items-center gap-2">
							<span>{new Date(session.creationDtm).toLocaleDateString('en-US')}</span>
							{!session?.isCurrent && (
								<button
									onClick={() => logoutSession(session)}
									className="border grid place-items-center p-2 h-8 w-8 aspect-square leading-none"
								>
									X
								</button>
							)}
						</div>
					</li>
				))}
			</ul>
		</div>
	);
}
